### PR TITLE
Russian localisation and small fixes in the Example

### PR DESCRIPTION
**Pull request by K-Be**
Also I've added .gitignore and pods libraries to the git (Because .workspace file presents in the git).

### CODE REVIEW

**Comment by ashavit** [comment]
Hello @K-Be,
Before your code can be accepted into the project you must also sign the Contributor License Agreement (link below). Please email me a signed copy.

Also, please revert the angry birds bundle changes.

[Autodesk Form Ind Contrib Agmt for ADAppRater.pdf](https://github.com/Autodesk/ADAppRater-iOS/files/197217/Autodesk.Form.Ind.Contrib.Agmt.for.ADAppRater.pdf)

Thanx.
Amir

**Comment by K-Be** [comment]
About licence, I'll  read it. 
About bundle ID, can you select some bundle id for example project. I think is not clear to provide not complete example (without some correct bundle id example does not work).

**Comment by ashavit** [comment]
I accept your approach and I'll insert our app's bundle.
I just don't think it is ok to use an unrelated third party's bundle for that matter.

**Comment by K-Be** [comment]
Sorry, what is  "our app's bundle"? 
Do you talk about "com.autodesk.apprater.demo" bundle id? With this bundle id I can't run example to exam library. Or do you talk about some other your product?

**Comment by ashavit** [comment]
Some other product

**Comment by K-Be** [comment]
Ok, write here bundle id and I'll change it.

**Comment by ashavit** [comment]
com.autodesk.autocadws
thanx

**Comment by K-Be** [comment]
I've sent the signed agreement.

**Pull request merged**
